COBOL68スタイルのデータ記述項におけるCOPY動作(cobol68-copy-in-data-description) COBOL68 style COPY semantics in data description clause (when conf.parameter cobol68-copy-in-data-description: yes).

diff --git a/tests/jp-compat b/tests/jp-compat
--- a/tests/jp-compat
+++ b/tests/jp-compat
@@ -303,7 +303,7 @@ at_times_file=$at_suite_dir/at-times
 # List of the tested programs.
 at_tested='cobc'
 # List of the all the test groups.
-at_groups_all=' 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79'
+at_groups_all=' 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84'
 # As many dots as there are digits in the last test group number.
 # Used to normalize the test group numbers so that `ls' lists them in
 # numerical order.
@@ -382,12 +382,17 @@ at_help_all='1;split-keys.at:1;SPLIT KEYS (ALTERNATE KEY);;
 71;job-date.at:92;COB_DATE FUNC. CURRENT-DATE;;
 72;nibble-c-for-unsigned.at:1;Decimal nibble C as unsigned;;
 73;upsi-x.at:1;UPSI-x;;
-74;switch-no-mnemonic.at:1;SWITCH-x with no mnemonic name;;
-75;data-desc-no-dot.at:1;Data description unterminated;;
-76;data-desc-no-dot.at:20;Data desc. ambiguous level-num 1;;
-77;data-desc-no-dot.at:39;Data desc. ambiguous level-num 2;;
-78;data-desc-no-dot.at:59;Data desc. level-num error after 88;;
-79;data-desc-no-dot.at:83;Data desc. ambiguous level-num (degrade check);;
+74;cob68-copy.at:1;COBOL68 COPY;;
+75;cob68-copy.at:25;COBOL68 COPY nested;;
+76;cob68-copy.at:53;COBOL68 COPY nested fragments;;
+77;cob68-copy.at:81;COBOL68 COPY nested w/ normal;;
+78;cob68-copy.at:109;COBOL68 COPY nested w/ normal 2;;
+79;switch-no-mnemonic.at:1;SWITCH-x with no mnemonic name;;
+80;data-desc-no-dot.at:1;Data description unterminated;;
+81;data-desc-no-dot.at:20;Data desc. ambiguous level-num 1;;
+82;data-desc-no-dot.at:39;Data desc. ambiguous level-num 2;;
+83;data-desc-no-dot.at:59;Data desc. level-num error after 88;;
+84;data-desc-no-dot.at:83;Data desc. ambiguous level-num (degrade check);;
 '
 
 at_keywords=
@@ -8319,13 +8324,477 @@ $at_traceon
     at_status=`cat $at_status_file`
     ;;
 
-  74 ) # 74. switch-no-mnemonic.at:1: SWITCH-x with no mnemonic name
-    at_setup_line='switch-no-mnemonic.at:1'
-    at_desc='SWITCH-x with no mnemonic name'
-    $at_quiet $ECHO_N " 74: SWITCH-x with no mnemonic name               $ECHO_C"
+  74 ) # 74. cob68-copy.at:1: COBOL68 COPY
+    at_setup_line='cob68-copy.at:1'
+    at_desc='COBOL68 COPY'
+    $at_quiet $ECHO_N " 74: COBOL68 COPY                                 $ECHO_C"
     at_xfail=no
     (
-      echo "74. switch-no-mnemonic.at:1: testing ..."
+      echo "74. cob68-copy.at:1: testing ..."
+      $at_traceon
+
+
+cat >prog.cob <<'_ATEOF'
+
+       IDENTIFICATION   DIVISION.
+       PROGRAM-ID.      prog.
+       DATA             DIVISION.
+       WORKING-STORAGE  SECTION.
+       01 X-01 COPY inc1.
+       PROCEDURE        DIVISION.
+           DISPLAY X-01 WITH NO ADVANCING.
+          GOBACK.
+_ATEOF
+
+
+cat >inc1.cpy <<'_ATEOF'
+
+       01 X-NN.
+           03 X-11 PIC X VALUE 'A'.
+           03 X-12 PIC X VALUE 'B'.
+           03 X-13 PIC X VALUE 'C'.
+_ATEOF
+
+
+$at_traceoff
+echo "cob68-copy.at:21: \${COMPILE_JP_COMPAT} prog.cob"
+echo cob68-copy.at:21 >$at_check_line_file
+( $at_traceon; ${COMPILE_JP_COMPAT} prog.cob ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+$at_diff $at_devnull $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "cob68-copy.at:21: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+$at_traceoff
+echo "cob68-copy.at:22: ./prog"
+echo cob68-copy.at:22 >$at_check_line_file
+( $at_traceon; ./prog ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+echo >>$at_stdout; echo "ABC" | $at_diff - $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "cob68-copy.at:22: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+      $at_traceoff
+      $at_times_p && times >$at_times_file
+    ) 5>&1 2>&1 | eval $at_tee_pipe
+    at_status=`cat $at_status_file`
+    ;;
+
+  75 ) # 75. cob68-copy.at:25: COBOL68 COPY nested
+    at_setup_line='cob68-copy.at:25'
+    at_desc='COBOL68 COPY nested'
+    $at_quiet $ECHO_N " 75: COBOL68 COPY nested                          $ECHO_C"
+    at_xfail=no
+    (
+      echo "75. cob68-copy.at:25: testing ..."
+      $at_traceon
+
+
+cat >prog.cob <<'_ATEOF'
+
+       IDENTIFICATION   DIVISION.
+       PROGRAM-ID.      prog.
+       DATA             DIVISION.
+       WORKING-STORAGE  SECTION.
+       01 X-01 COPY inc1.
+       PROCEDURE        DIVISION.
+           DISPLAY X-01 WITH NO ADVANCING.
+          GOBACK.
+_ATEOF
+
+
+cat >inc1.cpy <<'_ATEOF'
+
+       01 X-N1 COPY inc2.
+_ATEOF
+
+
+cat >inc2.cpy <<'_ATEOF'
+
+       01 X-N2.
+           03 X-11 PIC X VALUE 'A'.
+           03 X-12 PIC X VALUE 'B'.
+           03 X-13 PIC X VALUE 'C'.
+_ATEOF
+
+
+$at_traceoff
+echo "cob68-copy.at:49: \${COMPILE_JP_COMPAT} prog.cob"
+echo cob68-copy.at:49 >$at_check_line_file
+( $at_traceon; ${COMPILE_JP_COMPAT} prog.cob ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+$at_diff $at_devnull $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "cob68-copy.at:49: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+$at_traceoff
+echo "cob68-copy.at:50: ./prog"
+echo cob68-copy.at:50 >$at_check_line_file
+( $at_traceon; ./prog ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+echo >>$at_stdout; echo "ABC" | $at_diff - $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "cob68-copy.at:50: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+      $at_traceoff
+      $at_times_p && times >$at_times_file
+    ) 5>&1 2>&1 | eval $at_tee_pipe
+    at_status=`cat $at_status_file`
+    ;;
+
+  76 ) # 76. cob68-copy.at:53: COBOL68 COPY nested fragments
+    at_setup_line='cob68-copy.at:53'
+    at_desc='COBOL68 COPY nested fragments'
+    $at_quiet $ECHO_N " 76: COBOL68 COPY nested fragments                $ECHO_C"
+    at_xfail=no
+    (
+      echo "76. cob68-copy.at:53: testing ..."
+      $at_traceon
+
+
+cat >prog.cob <<'_ATEOF'
+
+       IDENTIFICATION   DIVISION.
+       PROGRAM-ID.      prog.
+       DATA             DIVISION.
+       WORKING-STORAGE  SECTION.
+       01 X-01 COPY inc1.
+       PROCEDURE        DIVISION.
+           DISPLAY X-01 WITH NO ADVANCING.
+          GOBACK.
+_ATEOF
+
+
+cat >inc1.cpy <<'_ATEOF'
+
+       01 X-N1 COPY inc2.
+           03 X-12 PIC X VALUE 'B'.
+           03 X-13 PIC X VALUE 'C'.
+_ATEOF
+
+
+cat >inc2.cpy <<'_ATEOF'
+
+       01 X-N2.
+           03 X-11 PIC X VALUE 'A'.
+_ATEOF
+
+
+$at_traceoff
+echo "cob68-copy.at:77: \${COMPILE_JP_COMPAT} prog.cob"
+echo cob68-copy.at:77 >$at_check_line_file
+( $at_traceon; ${COMPILE_JP_COMPAT} prog.cob ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+$at_diff $at_devnull $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "cob68-copy.at:77: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+$at_traceoff
+echo "cob68-copy.at:78: ./prog"
+echo cob68-copy.at:78 >$at_check_line_file
+( $at_traceon; ./prog ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+echo >>$at_stdout; echo "ABC" | $at_diff - $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "cob68-copy.at:78: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+      $at_traceoff
+      $at_times_p && times >$at_times_file
+    ) 5>&1 2>&1 | eval $at_tee_pipe
+    at_status=`cat $at_status_file`
+    ;;
+
+  77 ) # 77. cob68-copy.at:81: COBOL68 COPY nested w/ normal
+    at_setup_line='cob68-copy.at:81'
+    at_desc='COBOL68 COPY nested w/ normal'
+    $at_quiet $ECHO_N " 77: COBOL68 COPY nested w/ normal                $ECHO_C"
+    at_xfail=no
+    (
+      echo "77. cob68-copy.at:81: testing ..."
+      $at_traceon
+
+
+cat >prog.cob <<'_ATEOF'
+
+       IDENTIFICATION   DIVISION.
+       PROGRAM-ID.      prog.
+       DATA             DIVISION.
+       WORKING-STORAGE  SECTION.
+       01 X-01 COPY inc1.
+       PROCEDURE        DIVISION.
+           DISPLAY X-01 WITH NO ADVANCING.
+          GOBACK.
+_ATEOF
+
+
+cat >inc1.cpy <<'_ATEOF'
+
+       COPY inc2.
+_ATEOF
+
+
+cat >inc2.cpy <<'_ATEOF'
+
+       01 X-N2.
+           03 X-11 PIC X VALUE 'A'.
+           03 X-12 PIC X VALUE 'B'.
+           03 X-13 PIC X VALUE 'C'.
+_ATEOF
+
+
+$at_traceoff
+echo "cob68-copy.at:105: \${COMPILE_JP_COMPAT} prog.cob"
+echo cob68-copy.at:105 >$at_check_line_file
+( $at_traceon; ${COMPILE_JP_COMPAT} prog.cob ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+$at_diff $at_devnull $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "cob68-copy.at:105: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+$at_traceoff
+echo "cob68-copy.at:106: ./prog"
+echo cob68-copy.at:106 >$at_check_line_file
+( $at_traceon; ./prog ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+echo >>$at_stdout; echo "ABC" | $at_diff - $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "cob68-copy.at:106: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+      $at_traceoff
+      $at_times_p && times >$at_times_file
+    ) 5>&1 2>&1 | eval $at_tee_pipe
+    at_status=`cat $at_status_file`
+    ;;
+
+  78 ) # 78. cob68-copy.at:109: COBOL68 COPY nested w/ normal 2
+    at_setup_line='cob68-copy.at:109'
+    at_desc='COBOL68 COPY nested w/ normal 2'
+    $at_quiet $ECHO_N " 78: COBOL68 COPY nested w/ normal 2              $ECHO_C"
+    at_xfail=no
+    (
+      echo "78. cob68-copy.at:109: testing ..."
+      $at_traceon
+
+
+cat >prog.cob <<'_ATEOF'
+
+       IDENTIFICATION   DIVISION.
+       PROGRAM-ID.      prog.
+       DATA             DIVISION.
+       WORKING-STORAGE  SECTION.
+       01 X-01 COPY inc1.
+       PROCEDURE        DIVISION.
+           DISPLAY X-01 WITH NO ADVANCING.
+          GOBACK.
+_ATEOF
+
+
+cat >inc1.cpy <<'_ATEOF'
+
+       01 X-N2.
+       COPY inc2.
+_ATEOF
+
+
+cat >inc2.cpy <<'_ATEOF'
+
+           03 X-11 PIC X VALUE 'A'.
+           03 X-12 PIC X VALUE 'B'.
+           03 X-13 PIC X VALUE 'C'.
+_ATEOF
+
+
+$at_traceoff
+echo "cob68-copy.at:133: \${COMPILE_JP_COMPAT} prog.cob"
+echo cob68-copy.at:133 >$at_check_line_file
+( $at_traceon; ${COMPILE_JP_COMPAT} prog.cob ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+$at_diff $at_devnull $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "cob68-copy.at:133: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+$at_traceoff
+echo "cob68-copy.at:134: ./prog"
+echo cob68-copy.at:134 >$at_check_line_file
+( $at_traceon; ./prog ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+echo >>$at_stdout; echo "ABC" | $at_diff - $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "cob68-copy.at:134: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+      $at_traceoff
+      $at_times_p && times >$at_times_file
+    ) 5>&1 2>&1 | eval $at_tee_pipe
+    at_status=`cat $at_status_file`
+    ;;
+
+  79 ) # 79. switch-no-mnemonic.at:1: SWITCH-x with no mnemonic name
+    at_setup_line='switch-no-mnemonic.at:1'
+    at_desc='SWITCH-x with no mnemonic name'
+    $at_quiet $ECHO_N " 79: SWITCH-x with no mnemonic name               $ECHO_C"
+    at_xfail=no
+    (
+      echo "79. switch-no-mnemonic.at:1: testing ..."
       $at_traceon
 
 
@@ -8420,13 +8889,13 @@ $at_traceon
     at_status=`cat $at_status_file`
     ;;
 
-  75 ) # 75. data-desc-no-dot.at:1: Data description unterminated
+  80 ) # 80. data-desc-no-dot.at:1: Data description unterminated
     at_setup_line='data-desc-no-dot.at:1'
     at_desc='Data description unterminated'
-    $at_quiet $ECHO_N " 75: Data description unterminated                $ECHO_C"
+    $at_quiet $ECHO_N " 80: Data description unterminated                $ECHO_C"
     at_xfail=no
     (
-      echo "75. data-desc-no-dot.at:1: testing ..."
+      echo "80. data-desc-no-dot.at:1: testing ..."
       $at_traceon
 
 
@@ -8501,13 +8970,13 @@ $at_traceon
     at_status=`cat $at_status_file`
     ;;
 
-  76 ) # 76. data-desc-no-dot.at:20: Data desc. ambiguous level-num 1
+  81 ) # 81. data-desc-no-dot.at:20: Data desc. ambiguous level-num 1
     at_setup_line='data-desc-no-dot.at:20'
     at_desc='Data desc. ambiguous level-num 1'
-    $at_quiet $ECHO_N " 76: Data desc. ambiguous level-num 1             $ECHO_C"
+    $at_quiet $ECHO_N " 81: Data desc. ambiguous level-num 1             $ECHO_C"
     at_xfail=no
     (
-      echo "76. data-desc-no-dot.at:20: testing ..."
+      echo "81. data-desc-no-dot.at:20: testing ..."
       $at_traceon
 
 
@@ -8582,13 +9051,13 @@ $at_traceon
     at_status=`cat $at_status_file`
     ;;
 
-  77 ) # 77. data-desc-no-dot.at:39: Data desc. ambiguous level-num 2
+  82 ) # 82. data-desc-no-dot.at:39: Data desc. ambiguous level-num 2
     at_setup_line='data-desc-no-dot.at:39'
     at_desc='Data desc. ambiguous level-num 2'
-    $at_quiet $ECHO_N " 77: Data desc. ambiguous level-num 2             $ECHO_C"
+    $at_quiet $ECHO_N " 82: Data desc. ambiguous level-num 2             $ECHO_C"
     at_xfail=no
     (
-      echo "77. data-desc-no-dot.at:39: testing ..."
+      echo "82. data-desc-no-dot.at:39: testing ..."
       $at_traceon
 
 
@@ -8664,13 +9133,13 @@ $at_traceon
     at_status=`cat $at_status_file`
     ;;
 
-  78 ) # 78. data-desc-no-dot.at:59: Data desc. level-num error after 88
+  83 ) # 83. data-desc-no-dot.at:59: Data desc. level-num error after 88
     at_setup_line='data-desc-no-dot.at:59'
     at_desc='Data desc. level-num error after 88'
-    $at_quiet $ECHO_N " 78: Data desc. level-num error after 88          $ECHO_C"
+    $at_quiet $ECHO_N " 83: Data desc. level-num error after 88          $ECHO_C"
     at_xfail=no
     (
-      echo "78. data-desc-no-dot.at:59: testing ..."
+      echo "83. data-desc-no-dot.at:59: testing ..."
       $at_traceon
 
 
@@ -8701,7 +9170,7 @@ at_status=$?
 grep '^ *+' $at_stder1 >&2
 grep -v '^ *+' $at_stder1 >$at_stderr
 at_failed=false
-echo >>$at_stderr; echo "prog.cob:13: Error: syntax error, unexpected Identifier, expecting end of file or FUNCTION-ID or PROGRAM-ID
+echo >>$at_stderr; echo "prog.cob:10: Error: syntax error, unexpected Identifier, expecting end of file or FUNCTION-ID or PROGRAM-ID
 " | $at_diff - $at_stderr || at_failed=:
 $at_diff $at_devnull $at_stdout || at_failed=:
 case $at_status in
@@ -8725,13 +9194,13 @@ $at_traceon
     at_status=`cat $at_status_file`
     ;;
 
-  79 ) # 79. data-desc-no-dot.at:83: Data desc. ambiguous level-num (degrade check)
+  84 ) # 84. data-desc-no-dot.at:83: Data desc. ambiguous level-num (degrade check)
     at_setup_line='data-desc-no-dot.at:83'
     at_desc='Data desc. ambiguous level-num (degrade check)'
-    $at_quiet $ECHO_N " 79: Data desc. ambiguous level-num (degrade check)$ECHO_C"
+    $at_quiet $ECHO_N " 84: Data desc. ambiguous level-num (degrade check)$ECHO_C"
     at_xfail=no
     (
-      echo "79. data-desc-no-dot.at:83: testing ..."
+      echo "84. data-desc-no-dot.at:83: testing ..."
       $at_traceon
 
 
