ASSIGN句ファイル名の解釈パターン追加('assign-clause: jph1') Added another device naming format in assign clause (when conf. parameter assign-clause: jph1).

diff --git a/tests/jp-compat b/tests/jp-compat
--- a/tests/jp-compat
+++ b/tests/jp-compat
@@ -303,7 +303,7 @@ at_times_file=$at_suite_dir/at-times
 # List of the tested programs.
 at_tested='cobc'
 # List of the all the test groups.
-at_groups_all=' 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60'
+at_groups_all=' 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64'
 # As many dots as there are digits in the last test group number.
 # Used to normalize the test group numbers so that `ls' lists them in
 # numerical order.
@@ -369,6 +369,10 @@ at_help_all='1;split-keys.at:1;SPLIT KEYS (ALTERNATE KEY);;
 58;copy-joining.at:102;COPY JOINING EXISTING NAME;;
 59;copy-joining.at:127;COPY JOINING Group fields;;
 60;copy-joining.at:154;*NO* JOINING following JOINING ;;
+61;assign-devicename.at:1;ASSIGN coded device name;;
+62;assign-devicename.at:30;ASSIGN coded device w/o def.name;;
+63;assign-devicename.at:59;ASSIGN coded device name by env.var;;
+64;assign-devicename.at:88;ASSIGN coded device w/o def.name by env.var;;
 '
 
 at_keywords=
@@ -7026,6 +7030,378 @@ case $at_status in
             exit 77;;
    0) ;;
    *) echo "copy-joining.at:180: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+
+      $at_traceoff
+      $at_times_p && times >$at_times_file
+    ) 5>&1 2>&1 | eval $at_tee_pipe
+    at_status=`cat $at_status_file`
+    ;;
+
+  61 ) # 61. assign-devicename.at:1: ASSIGN coded device name
+    at_setup_line='assign-devicename.at:1'
+    at_desc='ASSIGN coded device name'
+    $at_quiet $ECHO_N " 61: ASSIGN coded device name                     $ECHO_C"
+    at_xfail=no
+    (
+      echo "61. assign-devicename.at:1: testing ..."
+      $at_traceon
+
+
+cat >TEST1 <<'_ATEOF'
+OK.
+_ATEOF
+
+
+cat >prog.cob <<'_ATEOF'
+
+       IDENTIFICATION   DIVISION.
+       PROGRAM-ID.      prog.
+       ENVIRONMENT      DIVISION.
+       INPUT-OUTPUT     SECTION.
+       FILE-CONTROL.
+       SELECT F01 ASSIGN TO SYS01-DA-DK-S-TEST1
+                  ORGANIZATION LINE SEQUENTIAL.
+       DATA             DIVISION.
+       FILE             SECTION.
+       FD  F01.
+       01  F01R         PIC X(8).
+       PROCEDURE        DIVISION.
+           OPEN INPUT F01.
+           READ F01.
+           DISPLAY F01R WITH NO ADVANCING.
+           CLOSE F01.
+_ATEOF
+
+
+$at_traceoff
+echo "assign-devicename.at:25: \${COMPILE_JP_COMPAT} prog.cob"
+echo assign-devicename.at:25 >$at_check_line_file
+( $at_traceon; ${COMPILE_JP_COMPAT} prog.cob ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+$at_diff $at_devnull $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "assign-devicename.at:25: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+$at_traceoff
+echo "assign-devicename.at:26: ./prog"
+echo assign-devicename.at:26 >$at_check_line_file
+( $at_traceon; ./prog ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+echo >>$at_stdout; echo "OK.     " | $at_diff - $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "assign-devicename.at:26: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+
+      $at_traceoff
+      $at_times_p && times >$at_times_file
+    ) 5>&1 2>&1 | eval $at_tee_pipe
+    at_status=`cat $at_status_file`
+    ;;
+
+  62 ) # 62. assign-devicename.at:30: ASSIGN coded device w/o def.name
+    at_setup_line='assign-devicename.at:30'
+    at_desc='ASSIGN coded device w/o def.name'
+    $at_quiet $ECHO_N " 62: ASSIGN coded device w/o def.name             $ECHO_C"
+    at_xfail=no
+    (
+      echo "62. assign-devicename.at:30: testing ..."
+      $at_traceon
+
+
+cat >SYS01 <<'_ATEOF'
+OK.
+_ATEOF
+
+
+cat >prog.cob <<'_ATEOF'
+
+       IDENTIFICATION   DIVISION.
+       PROGRAM-ID.      prog.
+       ENVIRONMENT      DIVISION.
+       INPUT-OUTPUT     SECTION.
+       FILE-CONTROL.
+       SELECT F01 ASSIGN TO SYS01-DA-DK-S
+                  ORGANIZATION LINE SEQUENTIAL.
+       DATA             DIVISION.
+       FILE             SECTION.
+       FD  F01.
+       01  F01R         PIC X(8).
+       PROCEDURE        DIVISION.
+           OPEN INPUT F01.
+           READ F01.
+           DISPLAY F01R WITH NO ADVANCING.
+           CLOSE F01.
+_ATEOF
+
+
+$at_traceoff
+echo "assign-devicename.at:54: \${COMPILE_JP_COMPAT} prog.cob"
+echo assign-devicename.at:54 >$at_check_line_file
+( $at_traceon; ${COMPILE_JP_COMPAT} prog.cob ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+$at_diff $at_devnull $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "assign-devicename.at:54: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+$at_traceoff
+echo "assign-devicename.at:55: ./prog"
+echo assign-devicename.at:55 >$at_check_line_file
+( $at_traceon; ./prog ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+echo >>$at_stdout; echo "OK.     " | $at_diff - $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "assign-devicename.at:55: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+
+      $at_traceoff
+      $at_times_p && times >$at_times_file
+    ) 5>&1 2>&1 | eval $at_tee_pipe
+    at_status=`cat $at_status_file`
+    ;;
+
+  63 ) # 63. assign-devicename.at:59: ASSIGN coded device name by env.var
+    at_setup_line='assign-devicename.at:59'
+    at_desc='ASSIGN coded device name by env.var'
+    $at_quiet $ECHO_N " 63: ASSIGN coded device name by env.var          $ECHO_C"
+    at_xfail=no
+    (
+      echo "63. assign-devicename.at:59: testing ..."
+      $at_traceon
+
+
+cat >datafile <<'_ATEOF'
+OK.
+_ATEOF
+
+
+cat >prog.cob <<'_ATEOF'
+
+       IDENTIFICATION   DIVISION.
+       PROGRAM-ID.      prog.
+       ENVIRONMENT      DIVISION.
+       INPUT-OUTPUT     SECTION.
+       FILE-CONTROL.
+       SELECT F01 ASSIGN TO SYS01-DA-DK-S-TEST1
+                  ORGANIZATION LINE SEQUENTIAL.
+       DATA             DIVISION.
+       FILE             SECTION.
+       FD  F01.
+       01  F01R         PIC X(8).
+       PROCEDURE        DIVISION.
+           OPEN INPUT F01.
+           READ F01.
+           DISPLAY F01R WITH NO ADVANCING.
+           CLOSE F01.
+_ATEOF
+
+
+$at_traceoff
+echo "assign-devicename.at:83: \${COMPILE_JP_COMPAT} prog.cob"
+echo assign-devicename.at:83 >$at_check_line_file
+( $at_traceon; ${COMPILE_JP_COMPAT} prog.cob ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+$at_diff $at_devnull $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "assign-devicename.at:83: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+$at_traceoff
+echo "assign-devicename.at:84: TEST1=datafile ./prog"
+echo assign-devicename.at:84 >$at_check_line_file
+( $at_traceon; TEST1=datafile ./prog ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+echo >>$at_stdout; echo "OK.     " | $at_diff - $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "assign-devicename.at:84: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+
+      $at_traceoff
+      $at_times_p && times >$at_times_file
+    ) 5>&1 2>&1 | eval $at_tee_pipe
+    at_status=`cat $at_status_file`
+    ;;
+
+  64 ) # 64. assign-devicename.at:88: ASSIGN coded device w/o def.name by env.var
+    at_setup_line='assign-devicename.at:88'
+    at_desc='ASSIGN coded device w/o def.name by env.var'
+    $at_quiet $ECHO_N " 64: ASSIGN coded device w/o def.name by env.var  $ECHO_C"
+    at_xfail=no
+    (
+      echo "64. assign-devicename.at:88: testing ..."
+      $at_traceon
+
+
+cat >datafile <<'_ATEOF'
+OK.
+_ATEOF
+
+
+cat >prog.cob <<'_ATEOF'
+
+       IDENTIFICATION   DIVISION.
+       PROGRAM-ID.      prog.
+       ENVIRONMENT      DIVISION.
+       INPUT-OUTPUT     SECTION.
+       FILE-CONTROL.
+       SELECT F01 ASSIGN TO SYS01-DA-DK-S
+                  ORGANIZATION LINE SEQUENTIAL.
+       DATA             DIVISION.
+       FILE             SECTION.
+       FD  F01.
+       01  F01R         PIC X(8).
+       PROCEDURE        DIVISION.
+           OPEN INPUT F01.
+           READ F01.
+           DISPLAY F01R WITH NO ADVANCING.
+           CLOSE F01.
+_ATEOF
+
+
+$at_traceoff
+echo "assign-devicename.at:112: \${COMPILE_JP_COMPAT} prog.cob"
+echo assign-devicename.at:112 >$at_check_line_file
+( $at_traceon; ${COMPILE_JP_COMPAT} prog.cob ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+$at_diff $at_devnull $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "assign-devicename.at:112: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+$at_traceoff
+echo "assign-devicename.at:113: SYS01=datafile ./prog"
+echo assign-devicename.at:113 >$at_check_line_file
+( $at_traceon; SYS01=datafile ./prog ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+echo >>$at_stdout; echo "OK.     " | $at_diff - $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "assign-devicename.at:113: exit code was $at_status, expected 0"
       at_failed=:;;
 esac
 if $at_failed; then
