字類検査においてPIC 9項目の値に符号ニブル'C'を許す(COB_NIBBLE_C_UNSIGNED) Treat sign-nibble 'C' as 'F' in unsigned packed numeric value,  when also type checking(when set COB_NIBBLE_C_UNSIGNED).

diff --git a/tests/jp-compat b/tests/jp-compat
--- a/tests/jp-compat
+++ b/tests/jp-compat
@@ -303,7 +303,7 @@ at_times_file=$at_suite_dir/at-times
 # List of the tested programs.
 at_tested='cobc'
 # List of the all the test groups.
-at_groups_all=' 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70'
+at_groups_all=' 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71'
 # As many dots as there are digits in the last test group number.
 # Used to normalize the test group numbers so that `ls' lists them in
 # numerical order.
@@ -379,6 +379,7 @@ at_help_all='1;split-keys.at:1;SPLIT KEYS (ALTERNATE KEY);;
 68;job-date.at:48;COB_DATE DAY;;
 69;job-date.at:70;COB_DATE DAY YYYYDDD;;
 70;job-date.at:92;COB_DATE FUNC. CURRENT-DATE;;
+71;nibble-c-for-unsigned.at:1;Decimal nibble C as unsigned;;
 '
 
 at_keywords=
@@ -7972,6 +7973,121 @@ case $at_status in
             exit 77;;
    0) ;;
    *) echo "job-date.at:111: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+
+      $at_traceoff
+      $at_times_p && times >$at_times_file
+    ) 5>&1 2>&1 | eval $at_tee_pipe
+    at_status=`cat $at_status_file`
+    ;;
+
+  71 ) # 71. nibble-c-for-unsigned.at:1: Decimal nibble C as unsigned
+    at_setup_line='nibble-c-for-unsigned.at:1'
+    at_desc='Decimal nibble C as unsigned'
+    $at_quiet $ECHO_N " 71: Decimal nibble C as unsigned                 $ECHO_C"
+    at_xfail=no
+    (
+      echo "71. nibble-c-for-unsigned.at:1: testing ..."
+      $at_traceon
+
+
+cat >prog.cob <<'_ATEOF'
+
+       IDENTIFICATION   DIVISION.
+       PROGRAM-ID.      prog.
+       DATA             DIVISION.
+       WORKING-STORAGE  SECTION.
+       01  UNI01.
+         03 SIGNED01.
+           05 SDEC01 PIC S9(2) COMP-3.
+         03 UNSIGNED01 REDEFINES SIGNED01.
+           05 UDEC01 PIC  9(2) COMP-3.
+       PROCEDURE        DIVISION.
+           MOVE 1 TO SDEC01.
+           IF SDEC01 IS NUMERIC THEN
+               DISPLAY "S" WITH NO ADVANCING
+           END-IF.
+           IF UDEC01 IS NUMERIC THEN
+               DISPLAY "U" WITH NO ADVANCING
+           END-IF.
+           STOP RUN.
+_ATEOF
+
+
+$at_traceoff
+echo "nibble-c-for-unsigned.at:24: \${COMPILE} prog.cob"
+echo nibble-c-for-unsigned.at:24 >$at_check_line_file
+( $at_traceon; ${COMPILE} prog.cob ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+$at_diff $at_devnull $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "nibble-c-for-unsigned.at:24: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+$at_traceoff
+echo "nibble-c-for-unsigned.at:25: ./prog"
+echo nibble-c-for-unsigned.at:25 >$at_check_line_file
+( $at_traceon; ./prog ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+echo >>$at_stdout; echo "S" | $at_diff - $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "nibble-c-for-unsigned.at:25: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+$at_traceoff
+echo "nibble-c-for-unsigned.at:26: COB_NIBBLE_C_UNSIGNED=Y ./prog"
+echo nibble-c-for-unsigned.at:26 >$at_check_line_file
+( $at_traceon; COB_NIBBLE_C_UNSIGNED=Y ./prog ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+echo >>$at_stdout; echo "SU" | $at_diff - $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "nibble-c-for-unsigned.at:26: exit code was $at_status, expected 0"
       at_failed=:;;
 esac
 if $at_failed; then
