SEARCH文WHEN節でキー項目名を条件式右オペランドに書くのを許す(allow-search-key-in-rhs) Accept key field name on right hand side of WHEN expression in SEARCH statement (when conf.parameter allow-search-key-in-rhs: yes).

diff --git a/tests/jp-compat b/tests/jp-compat
--- a/tests/jp-compat
+++ b/tests/jp-compat
@@ -303,7 +303,7 @@ at_times_file=$at_suite_dir/at-times
 # List of the tested programs.
 at_tested='cobc'
 # List of the all the test groups.
-at_groups_all=' 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84'
+at_groups_all=' 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85'
 # As many dots as there are digits in the last test group number.
 # Used to normalize the test group numbers so that `ls' lists them in
 # numerical order.
@@ -393,6 +393,7 @@ at_help_all='1;split-keys.at:1;SPLIT KEYS (ALTERNATE KEY);;
 82;data-desc-no-dot.at:39;Data desc. ambiguous level-num 2;;
 83;data-desc-no-dot.at:59;Data desc. level-num error after 88;;
 84;data-desc-no-dot.at:83;Data desc. ambiguous level-num (degrade check);;
+85;search-key-in-rhs.at:1;SEARCH KEY IN RHS;;
 '
 
 at_keywords=
@@ -9232,6 +9233,104 @@ case $at_status in
             exit 77;;
    0) ;;
    *) echo "data-desc-no-dot.at:96: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+      $at_traceoff
+      $at_times_p && times >$at_times_file
+    ) 5>&1 2>&1 | eval $at_tee_pipe
+    at_status=`cat $at_status_file`
+    ;;
+
+  85 ) # 85. search-key-in-rhs.at:1: SEARCH KEY IN RHS
+    at_setup_line='search-key-in-rhs.at:1'
+    at_desc='SEARCH KEY IN RHS'
+    $at_quiet $ECHO_N " 85: SEARCH KEY IN RHS                            $ECHO_C"
+    at_xfail=no
+    (
+      echo "85. search-key-in-rhs.at:1: testing ..."
+      $at_traceon
+
+
+cat >prog.cob <<'_ATEOF'
+
+       IDENTIFICATION   DIVISION.
+       PROGRAM-ID.      prog.
+       DATA             DIVISION.
+       WORKING-STORAGE  SECTION.
+       01  WK00.
+         03 TBL00 OCCURS 5 TIMES
+                  ASCENDING KEY D0001
+                  INDEXED BY    TBL00-IDX.
+           05 D0001         PIC 9(4).
+           05 D0002         PIC X(4).
+       77  CNT00            PIC 9(4).
+       PROCEDURE        DIVISION.
+           MOVE 1 TO D0001(1).
+           MOVE 2 TO D0001(2).
+           MOVE 3 TO D0001(3).
+           MOVE 4 TO D0001(4).
+           MOVE 5 TO D0001(5).
+           MOVE "VAL1" TO D0002(1).
+           MOVE "VAL2" TO D0002(2).
+           MOVE "VAL3" TO D0002(3).
+           MOVE "VAL4" TO D0002(4).
+           MOVE "VAL5" TO D0002(5).
+           MOVE 3 TO CNT00.
+           SEARCH ALL TBL00 WHEN CNT00 = D0001(TBL00-IDX)
+               DISPLAY D0002(TBL00-IDX) WITH NO ADVANCING
+           END-SEARCH.
+           GOBACK.
+_ATEOF
+
+
+$at_traceoff
+echo "search-key-in-rhs.at:33: \${COMPILE_JP_COMPAT} prog.cob"
+echo search-key-in-rhs.at:33 >$at_check_line_file
+( $at_traceon; ${COMPILE_JP_COMPAT} prog.cob ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+$at_diff $at_devnull $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "search-key-in-rhs.at:33: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+$at_traceoff
+echo "search-key-in-rhs.at:34: ./prog"
+echo search-key-in-rhs.at:34 >$at_check_line_file
+( $at_traceon; ./prog ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+$at_diff $at_devnull $at_stderr || at_failed=:
+echo >>$at_stdout; echo "VAL3" | $at_diff - $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "search-key-in-rhs.at:34: exit code was $at_status, expected 0"
       at_failed=:;;
 esac
 if $at_failed; then
