テストの追加 Add test for recent changes.

diff --git a/tests/syntax b/tests/syntax
--- a/tests/syntax
+++ b/tests/syntax
@@ -303,7 +303,7 @@ at_times_file=$at_suite_dir/at-times
 # List of the tested programs.
 at_tested='cobc'
 # List of the all the test groups.
-at_groups_all=' 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88'
+at_groups_all=' 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91'
 # As many dots as there are digits in the last test group number.
 # Used to normalize the test group numbers so that `ls' lists them in
 # numerical order.
@@ -397,6 +397,9 @@ at_help_all='1;copy.at:22;COPY: file not found;copy;
 86;indicator.at:99;dollarif value match - not false;;
 87;indicator.at:119;column 7 is undefined value;;
 88;assign-external.at:1;ASSIGN TO DYNAMIC create file (assign_external);;
+89;error-recovery.at:1;parse-error recovery after Data desc.;;
+90;error-recovery.at:21;parse-error recovery after Headings.;;
+91;data-records.at:1;completely ignore DATA RECORDS;;
 '
 
 at_keywords=
@@ -6510,6 +6513,184 @@ case $at_status in
             exit 77;;
    0) ;;
    *) echo "assign-external.at:29: exit code was $at_status, expected 0"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+
+      $at_traceoff
+      $at_times_p && times >$at_times_file
+    ) 5>&1 2>&1 | eval $at_tee_pipe
+    at_status=`cat $at_status_file`
+    ;;
+
+  89 ) # 89. error-recovery.at:1: parse-error recovery after Data desc.
+    at_setup_line='error-recovery.at:1'
+    at_desc='parse-error recovery after Data desc.'
+    $at_quiet $ECHO_N " 89: parse-error recovery after Data desc.        $ECHO_C"
+    at_xfail=no
+    (
+      echo "89. error-recovery.at:1: testing ..."
+      $at_traceon
+
+
+cat >prog.cob <<'_ATEOF'
+
+       IDENTIFICATION   DIVISION.
+       PROGRAM-ID.      prog.
+       DATA             DIVISION.
+       WORKING-STORAGE  SECTION.
+       01  Y  PIC 9 VALUE.
+       01  X.
+       01  Z  PIC 9.
+       PROCEDURE        DIVISION.
+_ATEOF
+
+
+$at_traceoff
+echo "error-recovery.at:14: \${COMPILE} -o prog prog.cob"
+echo error-recovery.at:14 >$at_check_line_file
+( $at_traceon; ${COMPILE} -o prog prog.cob ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+echo >>$at_stderr; echo "prog.cob:6: Error: syntax error, unexpected '.'
+prog.cob:7: Error: PICTURE clause required for 'X'
+" | $at_diff - $at_stderr || at_failed=:
+$at_diff $at_devnull $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   1) ;;
+   *) echo "error-recovery.at:14: exit code was $at_status, expected 1"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+
+      $at_traceoff
+      $at_times_p && times >$at_times_file
+    ) 5>&1 2>&1 | eval $at_tee_pipe
+    at_status=`cat $at_status_file`
+    ;;
+
+  90 ) # 90. error-recovery.at:21: parse-error recovery after Headings.
+    at_setup_line='error-recovery.at:21'
+    at_desc='parse-error recovery after Headings.'
+    $at_quiet $ECHO_N " 90: parse-error recovery after Headings.         $ECHO_C"
+    at_xfail=no
+    (
+      echo "90. error-recovery.at:21: testing ..."
+      $at_traceon
+
+
+cat >prog.cob <<'_ATEOF'
+
+       IDENTIFICATION   DIVISION.
+       PROGRAM-ID.      prog.
+       DATA             DIVISION.
+       WORKING-STORAGE  SECTION.
+       01  Z  PIC 9.
+       PROCEDURE        DIVISION.
+       S00 SECTION SECTION
+           IF Z = 0 THEN
+               DISPLAY Z UPON NOWHERE
+               DISPLAY ZZ UPON CONSOLE
+           END-IF.
+_ATEOF
+
+
+$at_traceoff
+echo "error-recovery.at:37: \${COMPILE} -o prog prog.cob"
+echo error-recovery.at:37 >$at_check_line_file
+( $at_traceon; ${COMPILE} -o prog prog.cob ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+echo >>$at_stderr; echo "prog.cob:8: Error: syntax error, unexpected SECTION, expecting '.'
+prog.cob:10: Error: 'NOWHERE' undefined in SPECIAL-NAMES
+prog.cob:11: Error: 'ZZ' undefined
+" | $at_diff - $at_stderr || at_failed=:
+$at_diff $at_devnull $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   1) ;;
+   *) echo "error-recovery.at:37: exit code was $at_status, expected 1"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+
+      $at_traceoff
+      $at_times_p && times >$at_times_file
+    ) 5>&1 2>&1 | eval $at_tee_pipe
+    at_status=`cat $at_status_file`
+    ;;
+
+  91 ) # 91. data-records.at:1: completely ignore DATA RECORDS
+    at_setup_line='data-records.at:1'
+    at_desc='completely ignore DATA RECORDS'
+    $at_quiet $ECHO_N " 91: completely ignore DATA RECORDS               $ECHO_C"
+    at_xfail=no
+    (
+      echo "91. data-records.at:1: testing ..."
+      $at_traceon
+
+
+cat >prog.cob <<'_ATEOF'
+
+       IDENTIFICATION   DIVISION.
+       PROGRAM-ID.      prog.
+       ENVIRONMENT      DIVISION.
+       INPUT-OUTPUT     SECTION.
+       FILE-CONTROL.
+       SELECT TEST-FILE ASSIGN "TEST-FILE".
+       DATA             DIVISION.
+       FILE             SECTION.
+       FD TEST-FILE
+          DATA RECORD IS MISSING-REF.
+       01 TEST-RECORD.
+         03 TEST-KEY    PIC 9(10).
+_ATEOF
+
+
+$at_traceoff
+echo "data-records.at:18: \${COMPILE_ONLY} -std=cobol85 prog.cob"
+echo data-records.at:18 >$at_check_line_file
+( $at_traceon; ${COMPILE_ONLY} -std=cobol85 prog.cob ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+echo >>$at_stderr; echo "prog.cob:11: Warning: DATA RECORDS is obsolete in COBOL 85
+" | $at_diff - $at_stderr || at_failed=:
+$at_diff $at_devnull $at_stdout || at_failed=:
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   0) ;;
+   *) echo "data-records.at:18: exit code was $at_status, expected 0"
       at_failed=:;;
 esac
 if $at_failed; then
